language: php

php:
- 7.1
- 7.2
- 7.3

addons:
  code_climate:
    repo_token: 45818730a22e045eb76fddf6a2e987ddefecb491ae607d7942da18407d2bd4b2

branches:
  only:
  - master

before_script:
- composer self-update
- composer install --no-interaction

script:
- vendor/bin/phpunit --testdox

after_success:
  - vendor/bin/test-reporter
